language: python
python:
  - "3.6"
env:
  global:
    - DEBUG=True
    - ES_VERSION=6.6.1
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
    - ELASTICSEARCH_HOST=127.0.0.1
    - ELASTICSEARCH_AUTH=elastic:changeme
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - pip install -r requirements-dev.txt
before_script:
  - sudo service elasticsearch start
  - mkdir logging
  - chmod -R 777 logging
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - ./manage.py check
  - coverage run --source='.' ./manage.py test --settings=copernicus.testsettings
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
